[package]
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
description = "Agents for Yew"
documentation = "https://docs.rs/yew/"
edition = "2021"
homepage = "https://yew.rs"
license = "MIT OR Apache-2.0"
name = "yew-agent"
readme = "../../README.md"
repository = "https://github.com/yewstack/yew"
rust-version = "1.64.0"
version = "0.3.1"

[dependencies]
futures = "0.3"
gloo-worker = {version = "0.4", features = ["futures"]}
serde = {version = "1", features = ["derive"]}
wasm-bindgen = "0.2"
yew = {version = "0.21.0"}
yew-agent-macro = {version = "0.2"}

[dev-dependencies]
serde = "1.0.188"
